# Quartus II: Generate Tcl File for Project

# Close currently opened project if any
project close;

# Create and open the project
if {![project exists axusb]} {
	project create axusb;
}
project open axusb;

# Project Assignments
project start_batch "";

project add_assignment "" "" "" "" "FMAX_REQUIREMENT" "32.0 MHz";
project add_assignment "" "" "" "" "VERILOG_FILE" "synplify/axusb.vqm";
project add_assignment "" "" "" "" "COMPILER_SETTINGS" "axusb";
project add_assignment "" "" "" "" "SIMULATOR_SETTINGS" "axusb";
project end_batch "";

# Project Assignments and/or Default Parameter
project start_batch "";
project add_assignment "" "" "" "" "APEX20K_OPTIMIZATION_TECHNIQUE" "SPEED";
project add_assignment "" "" "" "" "APEX20K_TECHNOLOGY_MAPPER" "LUT";
project add_assignment "" "" "" "" "VERILOG_INPUT_VERSION" "VERILOG_2001";
project add_assignment "" "axusb" "" "" "EDA_BOARD_DESIGN_TOOL" "<NONE>";
project add_assignment "" "axusb" "" "" "EDA_DESIGN_ENTRY_SYNTHESIS_TOOL" "Synplify Pro";
project add_assignment "" "axusb" "" "" "EDA_FORMAL_VERIFICATION_TOOL" "<NONE>";
project add_assignment "" "axusb" "" "" "EDA_RESYNTHESIS_TOOL" "<NONE>";
project add_assignment "" "axusb" "" "" "EDA_SIMULATION_TOOL" "<NONE>";
project add_assignment "" "axusb" "" "" "EDA_TIMING_ANALYSIS_TOOL" "<NONE>";
project add_assignment "" "eda_design_synthesis" "" "" "EDA_INPUT_DATA_FORMAT" "VERILOG HDL";
project add_assignment "" "eda_design_synthesis" "" "" "EDA_INPUT_GND_NAME" "GND";
project add_assignment "" "eda_design_synthesis" "" "" "EDA_INPUT_VCC_NAME" "VCC";
project add_assignment "" "eda_design_synthesis" "" "" "EDA_RUN_TOOL_AUTOMATICALLY" "OFF";
project add_assignment "" "eda_design_synthesis" "" "" "EDA_OUTPUT_DATA_FORMAT" "EDIF";
project add_assignment "" "eda_design_synthesis" "" "" "EDA_SHOW_LMF_MAPPING_MESSAGES" "OFF";
project add_assignment "" "eda_design_synthesis" "" "" "EDA_LMF_FILE" "altsyn.lmf";
project add_assignment "" "eda_design_synthesis" "" "" "RESYNTHESIS_OPTIMIZATION_EFFORT" "NORMAL";
project add_assignment "" "eda_design_synthesis" "" "" "RESYNTHESIS_PHYSICAL_SYNTHESIS" "NORMAL";
project add_assignment "" "eda_design_synthesis" "" "" "RESYNTHESIS_RETIMING" "FULL";
project add_assignment "" "eda_design_synthesis" "" "" "USE_GENERATED_PHYSICAL_CONSTRAINTS" "ON";
project add_assignment "" "axusb" "" "" "SHOW_REGISTRATION_MESSAGE" "ON";
project end_batch "";

# Entity Assignments for axusb
project start_batch "axusb";
project add_assignment "axusb" "" "" "advn" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "cn7_a\[4\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[0\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[10\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[11\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[12\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[13\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[14\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[15\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[16\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[17\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[18\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[19\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[1\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[20\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[21\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[22\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[23\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[2\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[3\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[4\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[5\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[6\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[7\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[8\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ext_ab\[9\]" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "rwn" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ssram_ce2n" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ssram_cen" "FAST_OUTPUT_REGISTER" "ON";
project add_assignment "axusb" "" "" "ssram_oen" "FAST_OUTPUT_REGISTER" "ON";
project end_batch "axusb";

# Compiler Assignments for axusb
if {![project cmp_exists axusb]} {
	project create_cmp axusb;
}
project set_active_cmp axusb;

cmp start_batch;
cmp add_assignment "" "" "" "FOCUS_ENTITY_NAME" "|axusb";
cmp add_assignment "" "" "" "SAVE_DISK_SPACE" "ON";
cmp add_assignment "" "" "" "CLOCK_DIVISOR" "1";
cmp add_assignment "" "" "" "CLOCK_FREQUENCY" "32 MHZ";
cmp add_assignment "" "" "" "CLOCK_SOURCE" "INTERNAL";
cmp add_assignment "" "" "" "COMPRESSION_MODE" "OFF";
cmp add_assignment "" "" "" "APEX20K_CONFIG_DEVICE_JTAG_USER_CODE" "FFFFFFFF";
cmp add_assignment "" "" "" "GENERATE_CONFIG_HEXOUT_FILE" "OFF";
cmp add_assignment "" "" "" "GENERATE_CONFIG_ISC_FILE" "OFF";
cmp add_assignment "" "" "" "GENERATE_CONFIG_JAM_FILE" "OFF";
cmp add_assignment "" "" "" "GENERATE_CONFIG_JBC_FILE" "OFF";
cmp add_assignment "" "" "" "GENERATE_CONFIG_JBC_FILE_COMPRESSED" "ON";
cmp add_assignment "" "" "" "GENERATE_CONFIG_SVF_FILE" "OFF";
cmp add_assignment "" "" "" "GENERATE_HEX_FILE" "OFF";
cmp add_assignment "" "" "" "GENERATE_ISC_FILE" "OFF";
cmp add_assignment "" "" "" "GENERATE_JAM_FILE" "OFF";
cmp add_assignment "" "" "" "GENERATE_JBC_FILE" "OFF";
cmp add_assignment "" "" "" "GENERATE_JBC_FILE_COMPRESSED" "ON";
cmp add_assignment "" "" "" "GENERATE_RBF_FILE" "OFF";
cmp add_assignment "" "" "" "GENERATE_SVF_FILE" "OFF";
cmp add_assignment "" "" "" "GENERATE_TTF_FILE" "OFF";
cmp add_assignment "" "" "" "APEX20K_CONFIGURATION_SCHEME" "PASSIVE SERIAL";
cmp add_assignment "" "" "" "RESERVE_ALL_UNUSED_PINS" "AS OUTPUT DRIVING GROUND";
cmp add_assignment "" "" "" "RESERVE_PIN" "AS INPUT TRI-STATED";
cmp add_assignment "" "" "" "RESERVE_ASDO_AFTER_CONFIGURATION" "OFF";
cmp add_assignment "" "" "" "SECURITY_BIT" "OFF";
cmp add_assignment "" "" "" "APEX20K_JTAG_USER_CODE" "FFFFFFFF";
cmp add_assignment "" "" "" "USE_CHECKSUM_AS_USERCODE" "OFF";
cmp add_assignment "" "" "" "APEX20K_CONFIGURATION_DEVICE" "EPC2";
cmp add_assignment "" "" "" "USE_CONFIGURATION_DEVICE" "ON";
cmp add_assignment "axusb" "" "" "USER_LIBRARIES" "../axusb;../macro;../hdl";
cmp add_assignment "axusb" "" "" "DEVICE" "EP20K60EBC356-2X";
cmp add_assignment "axusb" "" "" "DEVICE_FILTER_PACKAGE" "BGA";
cmp add_assignment "axusb" "" "" "DEVICE_FILTER_PIN_COUNT" "356";
cmp add_assignment "axusb" "" "" "DEVICE_FILTER_SPEED_GRADE" "2";
cmp add_assignment "axusb" "" "" "GENERATE_HEX_FILE" "OFF";
cmp add_assignment "axusb" "" "" "GENERATE_RBF_FILE" "ON";
cmp add_assignment "axusb" "" "" "GENERATE_TTF_FILE" "OFF";
cmp add_assignment "axusb" "" "ax_ack64n" "LOCATION" "Pin_L5";
cmp add_assignment "axusb" "" "ax_ackn" "LOCATION" "Pin_K3";
cmp add_assignment "axusb" "" "ax_advn" "LOCATION" "Pin_AF23";
cmp add_assignment "axusb" "" "ax_bulkn" "LOCATION" "Pin_K4";
cmp add_assignment "axusb" "" "ax_bwan" "LOCATION" "Pin_AD24";
cmp add_assignment "axusb" "" "ax_bwbn" "LOCATION" "Pin_AE25";
cmp add_assignment "axusb" "" "ax_bwcn" "LOCATION" "Pin_AD23";
cmp add_assignment "axusb" "" "ax_bwdn" "LOCATION" "Pin_AD22";
cmp add_assignment "axusb" "" "ax_cken" "LOCATION" "Pin_AF25";
cmp add_assignment "axusb" "" "ax_clk" "LOCATION" "Pin_M23";
cmp add_assignment "axusb" "" "ax_clk24" "LOCATION" "Pin_R4";
cmp add_assignment "axusb" "" "ax_clkfbin" "LOCATION" "Pin_L25";
cmp add_assignment "axusb" "" "ax_cmdn" "LOCATION" "Pin_L4";
cmp add_assignment "axusb" "" "ax_ext_ab\[0\]" "LOCATION" "Pin_R26";
cmp add_assignment "axusb" "" "ax_ext_ab\[10\]" "LOCATION" "Pin_W26";
cmp add_assignment "axusb" "" "ax_ext_ab\[11\]" "LOCATION" "Pin_V23";
cmp add_assignment "axusb" "" "ax_ext_ab\[12\]" "LOCATION" "Pin_W24";
cmp add_assignment "axusb" "" "ax_ext_ab\[13\]" "LOCATION" "Pin_W23";
cmp add_assignment "axusb" "" "ax_ext_ab\[14\]" "LOCATION" "Pin_H22";
cmp add_assignment "axusb" "" "ax_ext_ab\[15\]" "LOCATION" "Pin_H23";
cmp add_assignment "axusb" "" "ax_ext_ab\[16\]" "LOCATION" "Pin_G25";
cmp add_assignment "axusb" "" "ax_ext_ab\[17\]" "LOCATION" "Pin_AF24";
cmp add_assignment "axusb" "" "ax_ext_ab\[18\]" "LOCATION" "Pin_H25";
cmp add_assignment "axusb" "" "ax_ext_ab\[19\]" "LOCATION" "Pin_H26";
cmp add_assignment "axusb" "" "ax_ext_ab\[1\]" "LOCATION" "Pin_R22";
cmp add_assignment "axusb" "" "ax_ext_ab\[20\]" "LOCATION" "Pin_J24";
cmp add_assignment "axusb" "" "ax_ext_ab\[21\]" "LOCATION" "Pin_K25";
cmp add_assignment "axusb" "" "ax_ext_ab\[22\]" "LOCATION" "Pin_L24";
cmp add_assignment "axusb" "" "ax_ext_ab\[23\]" "LOCATION" "Pin_M24";
cmp add_assignment "axusb" "" "ax_ext_ab\[2\]" "LOCATION" "Pin_T23";
cmp add_assignment "axusb" "" "ax_ext_ab\[3\]" "LOCATION" "Pin_U26";
cmp add_assignment "axusb" "" "ax_ext_ab\[4\]" "LOCATION" "Pin_U25";
cmp add_assignment "axusb" "" "ax_ext_ab\[5\]" "LOCATION" "Pin_U24";
cmp add_assignment "axusb" "" "ax_ext_ab\[6\]" "LOCATION" "Pin_V26";
cmp add_assignment "axusb" "" "ax_ext_ab\[7\]" "LOCATION" "Pin_U23";
cmp add_assignment "axusb" "" "ax_ext_ab\[8\]" "LOCATION" "Pin_U22";
cmp add_assignment "axusb" "" "ax_ext_ab\[9\]" "LOCATION" "Pin_V24";
cmp add_assignment "axusb" "" "ax_ext_db\[0\]" "LOCATION" "Pin_L26";
cmp add_assignment "axusb" "" "ax_ext_db\[10\]" "LOCATION" "Pin_C15";
cmp add_assignment "axusb" "" "ax_ext_db\[11\]" "LOCATION" "Pin_A16";
cmp add_assignment "axusb" "" "ax_ext_db\[12\]" "LOCATION" "Pin_B16";
cmp add_assignment "axusb" "" "ax_ext_db\[13\]" "LOCATION" "Pin_A17";
cmp add_assignment "axusb" "" "ax_ext_db\[14\]" "LOCATION" "Pin_C16";
cmp add_assignment "axusb" "" "ax_ext_db\[15\]" "LOCATION" "Pin_B17";
cmp add_assignment "axusb" "" "ax_ext_db\[16\]" "LOCATION" "Pin_A18";
cmp add_assignment "axusb" "" "ax_ext_db\[17\]" "LOCATION" "Pin_C17";
cmp add_assignment "axusb" "" "ax_ext_db\[18\]" "LOCATION" "Pin_A19";
cmp add_assignment "axusb" "" "ax_ext_db\[19\]" "LOCATION" "Pin_B19";
cmp add_assignment "axusb" "" "ax_ext_db\[1\]" "LOCATION" "Pin_B18";
cmp add_assignment "axusb" "" "ax_ext_db\[20\]" "LOCATION" "Pin_C18";
cmp add_assignment "axusb" "" "ax_ext_db\[21\]" "LOCATION" "Pin_A20";
cmp add_assignment "axusb" "" "ax_ext_db\[22\]" "LOCATION" "Pin_C19";
cmp add_assignment "axusb" "" "ax_ext_db\[23\]" "LOCATION" "Pin_A21";
cmp add_assignment "axusb" "" "ax_ext_db\[24\]" "LOCATION" "Pin_A22";
cmp add_assignment "axusb" "" "ax_ext_db\[25\]" "LOCATION" "Pin_B21";
cmp add_assignment "axusb" "" "ax_ext_db\[26\]" "LOCATION" "Pin_C20";
cmp add_assignment "axusb" "" "ax_ext_db\[27\]" "LOCATION" "Pin_A23";
cmp add_assignment "axusb" "" "ax_ext_db\[28\]" "LOCATION" "Pin_A24";
cmp add_assignment "axusb" "" "ax_ext_db\[29\]" "LOCATION" "Pin_B23";
cmp add_assignment "axusb" "" "ax_ext_db\[2\]" "LOCATION" "Pin_B20";
cmp add_assignment "axusb" "" "ax_ext_db\[30\]" "LOCATION" "Pin_C21";
cmp add_assignment "axusb" "" "ax_ext_db\[31\]" "LOCATION" "Pin_B24";
cmp add_assignment "axusb" "" "ax_ext_db\[32\]" "LOCATION" "Pin_C22";
cmp add_assignment "axusb" "" "ax_ext_db\[33\]" "LOCATION" "Pin_C23";
cmp add_assignment "axusb" "" "ax_ext_db\[34\]" "LOCATION" "Pin_B25";
cmp add_assignment "axusb" "" "ax_ext_db\[35\]" "LOCATION" "Pin_F26";
cmp add_assignment "axusb" "" "ax_ext_db\[3\]" "LOCATION" "Pin_B22";
cmp add_assignment "axusb" "" "ax_ext_db\[4\]" "LOCATION" "Pin_A25";
cmp add_assignment "axusb" "" "ax_ext_db\[5\]" "LOCATION" "Pin_C24";
cmp add_assignment "axusb" "" "ax_ext_db\[6\]" "LOCATION" "Pin_F24";
cmp add_assignment "axusb" "" "ax_ext_db\[7\]" "LOCATION" "Pin_G23";
cmp add_assignment "axusb" "" "ax_ext_db\[8\]" "LOCATION" "Pin_A13";
cmp add_assignment "axusb" "" "ax_ext_db\[9\]" "LOCATION" "Pin_A15";
cmp add_assignment "axusb" "" "ax_frdn" "LOCATION" "Pin_J3";
cmp add_assignment "axusb" "" "ax_fwrn" "LOCATION" "Pin_J2";
cmp add_assignment "axusb" "" "ax_keyin\[0\]" "LOCATION" "Pin_A7";
cmp add_assignment "axusb" "" "ax_keyin\[1\]" "LOCATION" "Pin_A6";
cmp add_assignment "axusb" "" "ax_keyin\[2\]" "LOCATION" "Pin_B7";
cmp add_assignment "axusb" "" "ax_keyin\[3\]" "LOCATION" "Pin_C8";
cmp add_assignment "axusb" "" "ax_keyout\[0\]" "LOCATION" "Pin_B9";
cmp add_assignment "axusb" "" "ax_keyout\[1\]" "LOCATION" "Pin_A8";
cmp add_assignment "axusb" "" "ax_keyout\[2\]" "LOCATION" "Pin_C9";
cmp add_assignment "axusb" "" "ax_keyout\[3\]" "LOCATION" "Pin_B8";
cmp add_assignment "axusb" "" "ax_lcd\[0\]" "LOCATION" "Pin_U2";
cmp add_assignment "axusb" "" "ax_lcd\[10\]" "LOCATION" "Pin_V5";
cmp add_assignment "axusb" "" "ax_lcd\[1\]" "LOCATION" "Pin_T5";
cmp add_assignment "axusb" "" "ax_lcd\[2\]" "LOCATION" "Pin_U3";
cmp add_assignment "axusb" "" "ax_lcd\[3\]" "LOCATION" "Pin_V1";
cmp add_assignment "axusb" "" "ax_lcd\[4\]" "LOCATION" "Pin_V2";
cmp add_assignment "axusb" "" "ax_lcd\[5\]" "LOCATION" "Pin_U5";
cmp add_assignment "axusb" "" "ax_lcd\[6\]" "LOCATION" "Pin_V3";
cmp add_assignment "axusb" "" "ax_lcd\[7\]" "LOCATION" "Pin_W1";
cmp add_assignment "axusb" "" "ax_lcd\[8\]" "LOCATION" "Pin_W2";
cmp add_assignment "axusb" "" "ax_lcd\[9\]" "LOCATION" "Pin_V4";
cmp add_assignment "axusb" "" "ax_led\[0\]" "LOCATION" "Pin_AF3";
cmp add_assignment "axusb" "" "ax_led\[10\]" "LOCATION" "Pin_AE7";
cmp add_assignment "axusb" "" "ax_led\[11\]" "LOCATION" "Pin_AF7";
cmp add_assignment "axusb" "" "ax_led\[12\]" "LOCATION" "Pin_AE8";
cmp add_assignment "axusb" "" "ax_led\[13\]" "LOCATION" "Pin_AD9";
cmp add_assignment "axusb" "" "ax_led\[14\]" "LOCATION" "Pin_AF8";
cmp add_assignment "axusb" "" "ax_led\[15\]" "LOCATION" "Pin_AE9";
cmp add_assignment "axusb" "" "ax_led\[1\]" "LOCATION" "Pin_AE4";
cmp add_assignment "axusb" "" "ax_led\[2\]" "LOCATION" "Pin_AF4";
cmp add_assignment "axusb" "" "ax_led\[3\]" "LOCATION" "Pin_AD6";
cmp add_assignment "axusb" "" "ax_led\[4\]" "LOCATION" "Pin_AE5";
cmp add_assignment "axusb" "" "ax_led\[5\]" "LOCATION" "Pin_AF5";
cmp add_assignment "axusb" "" "ax_led\[6\]" "LOCATION" "Pin_AD7";
cmp add_assignment "axusb" "" "ax_led\[7\]" "LOCATION" "Pin_AE6";
cmp add_assignment "axusb" "" "ax_led\[8\]" "LOCATION" "Pin_AF6";
cmp add_assignment "axusb" "" "ax_led\[9\]" "LOCATION" "Pin_AD8";
cmp add_assignment "axusb" "" "ax_linkn" "LOCATION" "Pin_T4";
cmp add_assignment "axusb" "" "ax_locked_out" "LOCATION" "Pin_T24";
cmp add_assignment "axusb" "" "ax_mode" "LOCATION" "Pin_AD21";
cmp add_assignment "axusb" "" "ax_mode_sel" "LOCATION" "Pin_K5";
cmp add_assignment "axusb" "" "ax_pll_clk" "LOCATION" "Pin_R23";
cmp add_assignment "axusb" "" "ax_rdn" "LOCATION" "Pin_K1";
cmp add_assignment "axusb" "" "ax_rgdtn" "LOCATION" "Pin_K2";
cmp add_assignment "axusb" "" "ax_rstn" "LOCATION" "Pin_L23";
cmp add_assignment "axusb" "" "ax_rwn" "LOCATION" "Pin_AE24";
cmp add_assignment "axusb" "" "ax_seg_db\[0\]" "LOCATION" "Pin_AD10";
cmp add_assignment "axusb" "" "ax_seg_db\[1\]" "LOCATION" "Pin_AF9";
cmp add_assignment "axusb" "" "ax_seg_db\[2\]" "LOCATION" "Pin_AE10";
cmp add_assignment "axusb" "" "ax_seg_db\[3\]" "LOCATION" "Pin_AD11";
cmp add_assignment "axusb" "" "ax_seg_db\[4\]" "LOCATION" "Pin_AF10";
cmp add_assignment "axusb" "" "ax_seg_db\[5\]" "LOCATION" "Pin_AE11";
cmp add_assignment "axusb" "" "ax_seg_db\[6\]" "LOCATION" "Pin_AF12";
cmp add_assignment "axusb" "" "ax_seg_db\[7\]" "LOCATION" "Pin_AE14";
cmp add_assignment "axusb" "" "ax_seg_sel\[0\]" "LOCATION" "Pin_R5";
cmp add_assignment "axusb" "" "ax_seg_sel\[1\]" "LOCATION" "Pin_T2";
cmp add_assignment "axusb" "" "ax_seg_sel\[2\]" "LOCATION" "Pin_T3";
cmp add_assignment "axusb" "" "ax_seg_sel\[3\]" "LOCATION" "Pin_U1";
cmp add_assignment "axusb" "" "ax_seg_sel\[4\]" "LOCATION" "Pin_AC4";
cmp add_assignment "axusb" "" "ax_seg_sel\[5\]" "LOCATION" "Pin_AC5";
cmp add_assignment "axusb" "" "ax_seg_sel\[6\]" "LOCATION" "Pin_AD3";
cmp add_assignment "axusb" "" "ax_seg_sel\[7\]" "LOCATION" "Pin_AE2";
cmp add_assignment "axusb" "" "ax_ssram_ce2n" "LOCATION" "Pin_H24";
cmp add_assignment "axusb" "" "ax_ssram_cen" "LOCATION" "Pin_AF22";
cmp add_assignment "axusb" "" "ax_ssram_oen" "LOCATION" "Pin_AD20";
cmp add_assignment "axusb" "" "ax_status" "LOCATION" "Pin_J1";
cmp add_assignment "axusb" "" "ax_sw\[0\]" "LOCATION" "Pin_AD5";
cmp add_assignment "axusb" "" "ax_sw\[1\]" "LOCATION" "Pin_AE3";
cmp add_assignment "axusb" "" "ax_sw\[2\]" "LOCATION" "Pin_AF2";
cmp add_assignment "axusb" "" "ax_sw\[3\]" "LOCATION" "Pin_AD4";
cmp add_assignment "axusb" "" "ax_usb_data\[0\]" "LOCATION" "Pin_N1";
cmp add_assignment "axusb" "" "ax_usb_data\[1\]" "LOCATION" "Pin_N2";
cmp add_assignment "axusb" "" "ax_usb_data\[2\]" "LOCATION" "Pin_M1";
cmp add_assignment "axusb" "" "ax_usb_data\[3\]" "LOCATION" "Pin_M2";
cmp add_assignment "axusb" "" "ax_usb_data\[4\]" "LOCATION" "Pin_M3";
cmp add_assignment "axusb" "" "ax_usb_data\[5\]" "LOCATION" "Pin_M4";
cmp add_assignment "axusb" "" "ax_usb_data\[6\]" "LOCATION" "Pin_L2";
cmp add_assignment "axusb" "" "ax_usb_data\[7\]" "LOCATION" "Pin_L3";
cmp add_assignment "axusb" "" "ax_zz" "LOCATION" "Pin_AE23";
cmp add_assignment "axusb" "" "ax_sp" "LOCATION" "Pin_T1";
cmp add_assignment "axusb" "" "R3_GND" "LOCATION" "Pin_R3";
cmp add_assignment "axusb" "" "R3_GND" "RESERVE_PIN" "As output driving ground"
cmp add_assignment "axusb" "" "" "RESERVE_ALL_UNUSED_PINS" "AS INPUT TRI-STATED";
cmp end_batch;

# Compile: axusb
project set_active_cmp axusb;
cmp start compile;
while {[cmp is_running]} {
	if {![is_command_line_mode]} {
		set x 0;
		after 1000 {set x 1};
		vwait x;
	}
	FlushEventQueue;
}
